### PR TITLE
fix: Make the path to the welcome image relative

### LINKED ISSUE #6: Thanks for your contribution to the Layer5 community! :tada:
The path to the welcome image needs fixed, so that it isn't broken in newly created repos from this template. It should remain a relative link.

```
Thanks for your contribution to the Layer5 community! :tada:
 
![Congrats!](../.github/welcome/Layer5-celebration.png)
```

_Originally posted by @welcome in https://github.com/layer5io/service-mesh-labs/pull/2#issuecomment-713312327_

### PR DESCRIPTION
**Pull request by HeroicHitesh**
**Description**
Make the path to the welcome image relative

This PR fixes #6 

**[Signed commits](CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — DISMISSED** [review]
Thank you, @HeroicHitesh. 👍

**Comment by leecalcote** [comment]
@HeroicHitesh will you take a moment to sign-off on your commit here? You can do so by following executing these instructions - https://github.com/layer5io/layer5-repo-template/pull/7/checks?check_run_id=1310222917.

See the welcome message above for how to have your committed automatically signed-off.

**Comment by HeroicHitesh** [comment]
> @HeroicHitesh will you take a moment to sign-off on your commit here? You can do so by following executing these instructions - https://github.com/layer5io/layer5-repo-template/pull/7/checks?check_run_id=1310222917.
> 
> See the welcome message above for how to have your committed automatically signed-off.

@leecalcote Done

**Comment by leecalcote** [comment]
Thanks for giving this a shot, @HeroicHitesh. Will you take another crack at it (see the message from the Welcome bot above)?

**Pull request merged**
